[toolchain]
anchor_version = "0.30.0"
solana_version = "2.1.5"
channel = "stable"

[features]
seeds = false
skip-lint = false

[programs.localnet]
gorbagana_slots = "BqF33RrRRXQ78AtU98kXGyLNuCgd1zmNd4HCJBoJf5G5"

[programs.testnet]
gorbagana_slots = "BqF33RrRRXQ78AtU98kXGyLNuCgd1zmNd4HCJBoJf5G5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.gorbagana.wtf/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
